# Generated by Django 3.1.7 on 2021-03-23 10:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='oem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('oem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='device.oem')),
            ],
        ),
        migrations.CreateModel(
            name='device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=225, unique=True)),
                ('wfi_mac', models.CharField(blank=True, max_length=225, null=True)),
                ('iccid', models.CharField(blank=True, max_length=225, null=True)),
                ('imsi', models.CharField(blank=True, max_length=225, null=True)),
                ('mdn', models.CharField(blank=True, max_length=225, null=True)),
                ('assignee', models.CharField(blank=True, max_length=225, null=True)),
                ('assigned_date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 23, 15, 39, 2, 341702), null=True)),
                ('purpose', models.CharField(blank=True, max_length=225, null=True)),
                ('return_date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 23, 15, 39, 2, 341702), null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('delivery', models.CharField(choices=[('Early Dev Samples', 'Early Dev Samples'), ('Pre-LE', 'Pre-LE CROWN'), ('LE CROWN', 'LE CROWN'), ('FAI', 'FAI'), ('Marketing PR', 'Marketing PR')], default=('Early Dev Samples', 'Early Dev Samples'), max_length=225)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='device.model')),
                ('oem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='device.oem')),
            ],
        ),
    ]
