# Generated by Django 3.1.7 on 2021-04-05 11:15

import datetime
import device.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='assigned_date',
            field=models.CharField(blank=True, default=datetime.datetime(2021, 4, 5, 16, 45, 4, 794996), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='imei',
            field=models.CharField(max_length=15, unique=True, validators=[device.models.validate_imei]),
        ),
        migrations.AlterField(
            model_name='device',
            name='return_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
