# Generated by Django 3.1.7 on 2021-03-23 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='assigned_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 23, 19, 42, 7, 17186), null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='return_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 23, 19, 42, 7, 17186), null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='model',
            unique_together={('oem', 'name')},
        ),
    ]
