# Generated by Django 3.1.7 on 2021-04-09 07:55

import device.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='assigned_date',
            field=models.CharField(blank=True, default='04/09/2021', max_length=50, null=True, validators=[device.models.dateValidate], verbose_name='ASSIGNED DATE'),
        ),
        migrations.AlterField(
            model_name='device',
            name='imei',
            field=models.BigIntegerField(unique=True, validators=[device.models.validate_imei], verbose_name='IMEI'),
        ),
    ]
