# Generated by Django 3.1.7 on 2021-04-05 12:18

import datetime
import device.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20210405_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='assigned_date',
            field=models.CharField(blank=True, default=datetime.datetime(2021, 4, 5, 17, 48, 25, 115833), max_length=50, null=True, verbose_name='ASSIGNED DATE'),
        ),
        migrations.AlterField(
            model_name='device',
            name='assignee',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='ASSIGNEE'),
        ),
        migrations.AlterField(
            model_name='device',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='COMMENT'),
        ),
        migrations.AlterField(
            model_name='device',
            name='delivery',
            field=models.CharField(choices=[('Early Dev Samples', 'Early Dev Samples'), ('Pre-LE', 'Pre-LE'), ('LE', 'LE'), ('FAI', 'FAI'), ('FFW', 'FFW'), ('VIP KIT', 'VIP KIT')], default=('Early Dev Samples', 'Early Dev Samples'), max_length=225, verbose_name='DELIVERY'),
        ),
        migrations.AlterField(
            model_name='device',
            name='iccid',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='ICCID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='imei',
            field=models.CharField(max_length=15, unique=True, validators=[device.models.validate_imei], verbose_name='IMEI'),
        ),
        migrations.AlterField(
            model_name='device',
            name='imsi',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='IMSI'),
        ),
        migrations.AlterField(
            model_name='device',
            name='mdn',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='MDN'),
        ),
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='device.model', verbose_name='MODEL'),
        ),
        migrations.AlterField(
            model_name='device',
            name='oem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='device.oem', verbose_name='OEM'),
        ),
        migrations.AlterField(
            model_name='device',
            name='purpose',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='PURPOSE'),
        ),
        migrations.AlterField(
            model_name='device',
            name='return_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='RETURN DATE'),
        ),
        migrations.AlterField(
            model_name='device',
            name='wfi_mac',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='WFI MAC'),
        ),
    ]
