# Generated by Django 3.1.7 on 2021-03-26 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20210323_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='assigned_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 26, 16, 10, 21, 186664), null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='delivery',
            field=models.CharField(choices=[('Early Dev Samples', 'Early Dev Samples'), ('Pre-LE', 'Pre-LE'), ('LE', 'LE'), ('FAI', 'FAI'), ('FFW', 'FFW'), ('VIP KIT', 'VIP KIT')], default=('Early Dev Samples', 'Early Dev Samples'), max_length=225),
        ),
        migrations.AlterField(
            model_name='device',
            name='imei',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='return_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 26, 16, 10, 21, 186664), null=True),
        ),
    ]
