# Generated by Django 3.1.7 on 2021-04-07 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_auto_20210405_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='assigned_date',
            field=models.CharField(blank=True, default=datetime.datetime(2021, 4, 7, 18, 51, 55, 176911), max_length=50, null=True, verbose_name='ASSIGNED DATE'),
        ),
    ]
