# Generated by Django 3.1.7 on 2021-04-07 13:51

import datetime
import device.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_auto_20210407_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='assigned_date',
            field=models.CharField(blank=True, default=datetime.datetime(2021, 4, 7, 19, 21, 49, 926205), max_length=50, null=True, validators=[device.models.dateValidate], verbose_name='ASSIGNED DATE'),
        ),
        migrations.AlterField(
            model_name='device',
            name='return_date',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[device.models.dateValidate], verbose_name='RETURN DATE'),
        ),
    ]
