# Generated by Django 3.1.7 on 2021-04-07 13:58

import datetime
import device.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_auto_20210407_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='assigned_date',
            field=models.CharField(blank=True, default=datetime.date(2021, 4, 7), max_length=50, null=True, validators=[device.models.dateValidate], verbose_name='ASSIGNED DATE'),
        ),
    ]
