# Generated by Django 3.1.7 on 2021-04-08 10:38

import device.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_auto_20210408_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='assigned_date',
            field=models.CharField(blank=True, default='04/08/2021', max_length=50, null=True, validators=[device.models.dateValidate], verbose_name='ASSIGNED DATE'),
        ),
    ]
