# Generated by Django 3.1.7 on 2021-04-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_auto_20210408_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='assignee',
            field=models.CharField(blank=True, default=None, max_length=225, null=True, verbose_name='ASSIGNEE'),
        ),
    ]
